project overview - basic document
solana-rpc-community/rpc-v2-specs pull request #12
Opened 2023-11-13 18:20 UTC by grooviegermanikus

2023-11-14 22:08 UTC, buffalojoec commented on README.md
> +3. The reference implementation should provide a base level of service for local testing with modular options to scale up for mainnet.
I think between 1 and 2 we should have "establish a v2 interface for JSON RPC", and maybe even "with possible additional interfaces such as GraphQL, etc."

2023-11-14 22:08 UTC, buffalojoec commented on README.md
> +- Cluster -- metadata related to cluster performance, health, etc.
nit: for simplicity's sake I'd opt for dubbing `History` as `Blocks`, since blocks are really the parent of any transaction or history (chain) -related subject.

2024-03-05 14:29 UTC, godmodegalactus commented
@grooviegermanikus can you fix the comments

2024-03-06 13:49 UTC, godmodegalactus requested changes

2024-03-06 14:39 UTC, closed without merging

2024-03-06 14:39 UTC, grooviegermanikus commented
closing this, will create a very high-level readme and push down details to other places